status = error
name = CustomConfig

appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %msg%n

rootLogger.level = error
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console
